create schema if not exists cep;

create table cep.records
(
    id          bigint primary key generated by default as identity,
    status      text        not null,
    payload     text        not null,
    external_id bigint,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp
);

create index idx_records_status on cep.records (status);
create index idx_records_external_id on cep.records (external_id);

comment on table cep.records is 'Таблица для хранения записей, требующих обработки через внешний сервис';
comment on column cep.records.id is 'Уникальный идентификатор записи';
comment on column cep.records.status is 'Статус записи: CREATED или COMPLETE';
comment on column cep.records.payload is 'Данные для отправки во внешний сервис';
comment on column cep.records.external_id is 'ID, полученный от внешнего сервиса после успешной обработки';
comment on column cep.records.created_at is 'Дата и время создания записи';
comment on column cep.records.updated_at is 'Дата и время последнего обновления записи';
